version: '3'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - redis_data:/data
    depends_on:
      - postgres

  backend:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./services/backend/src:/app
      - ./services/utils:/app/utils
    command: uvicorn main_redis:app --reload --host 0.0.0.0 --port 5001
    depends_on:
      - redis

  frontend:
    restart: always
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8000:8000
    depends_on:
      - backend
    
  data_collection:
    env_file:
      - .env
    restart: always
    build: ./services/data-collection
    depends_on:
      - postgres
  
volumes:
  postgres_data:
  redis_data:
