version: '3'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    
  data_collection:
      env_file:
        - .env
      restart: always
      build:
        context: ./services/data-collection
        dockerfile: Dockerfile.data_collection
      depends_on:
        - postgres
  
  # data collection
  
volumes:
  postgres_data: