job_posting_thesaurus = {
    "developer": ["developer", "programmer", "coder", "software"],
    "data": ["data", "information", "intelligence"],
    "manager": ["manager", "supervisor", "team leader", "head", "director"],
    "remote": ["remote", "home", "virtual", "offsite", "telecommute", "distributed"],
    "full-time": ["full-time", "permanent"],
    "part-time": ["part-time", "temporary", "contract", "freelance", "hourly", "casual"],
    "marketing": ["marketing", "SEO", "branding"],
    "writer": ["writer", "copywriter", "author", "editor"],
    "consultant": ["consultant", "advisor", "consulting", "strategy", "management"],
    "service": ["service", "support", "client service", "help"],
    "HR": ["HR", "human resources", "HR manager", "recruitment", "talent"],
    "finance": ["finance", "accountant", "auditor", "controller", "finance consultant"],
    "education": ["education", "teacher", "educator", "instructor", "professor", "tutor"],
    "healthcare": ["healthcare", "nurse", "doctor", "medical", "pharmacist"],
    "intern": ["intern", "internship", "trainee", "apprentice"],
    "entry level": ["entry level", "junior", "associate", "beginner", "trainee", "starter"],
    "senior": ["senior", "lead", "principal", "chief"],
    "executive": ["executive", "CEO", "CFO", "CTO"],
    "programmer": ["developer", "programmer", "coder", "software"],
    "coder": ["developer", "programmer", "coder", "software"],
    "software": ["developer", "programmer", "coder", "software"],
    "information": ["data", "information", "intelligence"],
    "intelligence": ["data", "information", "intelligence"],
    "supervisor": ["manager", "supervisor", "team leader", "head", "director"],
    "team leader": ["manager", "supervisor", "team leader", "head", "director"],
    "head": ["manager", "supervisor", "team leader", "head", "director"],
    "director": ["manager", "supervisor", "team leader", "head", "director"],
    "home": ["remote", "home", "virtual", "offsite", "telecommute", "distributed"],
    "virtual": ["remote", "home", "virtual", "offsite", "telecommute", "distributed"],
    "offsite": ["remote", "home", "virtual", "offsite", "telecommute", "distributed"],
    "telecommute": ["remote", "home", "virtual", "offsite", "telecommute", "distributed"],
    "distributed": ["remote", "home", "virtual", "offsite", "telecommute", "distributed"],
    "permanent": ["full-time", "permanent"],
    "temporary": ["part-time", "temporary", "contract", "freelance", "hourly", "casual"],
    "contract": ["part-time", "temporary", "contract", "freelance", "hourly", "casual"],
    "freelance": ["part-time", "temporary", "contract", "freelance", "hourly", "casual"],
    "hourly": ["part-time", "temporary", "contract", "freelance", "hourly", "casual"],
    "casual": ["part-time", "temporary", "contract", "freelance", "hourly", "casual"],
    "SEO": ["marketing", "SEO", "branding"],
    "branding": ["marketing", "SEO", "branding"],
    "copywriter": ["writer", "copywriter", "author", "editor"],
    "author": ["writer", "copywriter", "author", "editor"],
    "editor": ["writer", "copywriter", "author", "editor"],
    "advisor": ["consultant", "advisor", "consulting", "strategy", "management"],
    "consulting": ["consultant", "advisor", "consulting", "strategy", "management"],
    "strategy": ["consultant", "advisor", "consulting", "strategy", "management"],
    "management": ["consultant", "advisor", "consulting", "strategy", "management"],
    "support": ["service", "support", "client service", "help"],
    "client service": ["service", "support", "client service", "help"],
    "help": ["service", "support", "client service", "help"],
    "human resources": ["HR", "human resources", "HR manager", "recruitment", "talent"],
    "HR manager": ["HR", "human resources", "HR manager", "recruitment", "talent"],
    "recruitment": ["HR", "human resources", "HR manager", "recruitment", "talent"],
    "talent": ["HR", "human resources", "HR manager", "recruitment", "talent"],
    "accountant": ["finance", "accountant", "auditor", "controller", "finance consultant"],
    "auditor": ["finance", "accountant", "auditor", "controller", "finance consultant"],
    "controller": ["finance", "accountant", "auditor", "controller", "finance consultant"],
    "finance consultant": ["finance", "accountant", "auditor", "controller", "finance consultant"],
    "teacher": ["education", "teacher", "educator", "instructor", "professor", "tutor"],
    "educator": ["education", "teacher", "educator", "instructor", "professor", "tutor"],
    "instructor": ["education", "teacher", "educator", "instructor", "professor", "tutor"],
    "professor": ["education", "teacher", "educator", "instructor", "professor", "tutor"],
    "tutor": ["education", "teacher", "educator", "instructor", "professor", "tutor"],
    "nurse": ["healthcare", "nurse", "doctor", "medical", "pharmacist"],
    "doctor": ["healthcare", "nurse", "doctor", "medical", "pharmacist"],
    "medical": ["healthcare", "nurse", "doctor", "medical", "pharmacist"],
    "pharmacist": ["healthcare", "nurse", "doctor", "medical", "pharmacist"],
    "internship": ["intern", "internship", "trainee", "apprentice"],
    "trainee": ["entry level", "junior", "associate", "beginner", "trainee", "starter"],
    "apprentice": ["intern", "internship", "trainee", "apprentice"],
    "junior": ["entry level", "junior", "associate", "beginner", "trainee", "starter"],
    "associate": ["entry level", "junior", "associate", "beginner", "trainee", "starter"],
    "beginner": ["entry level", "junior", "associate", "beginner", "trainee", "starter"],
    "starter": ["entry level", "junior", "associate", "beginner", "trainee", "starter"],
    "lead": ["senior", "lead", "principal", "chief"],
    "principal": ["senior", "lead", "principal", "chief"],
    "chief": ["senior", "lead", "principal", "chief"],
    "CEO": ["executive", "CEO", "CFO", "CTO"],
    "CFO": ["executive", "CEO", "CFO", "CTO"],
    "CTO": ["executive", "CEO", "CFO", "CTO"]
}